### PR TITLE
Add Utils unit tests

### PR DESCRIPTION
**Pull request by PSFW**
Hey @jeff-zucker, this is a minor contribution at the moment but I wanted to get this in early to see what your thoughts were. Please let me know if there is anything I should change about this.

I have had to increase the version of rdflib because of a transient dependency being too low for jest to work properly.
I have used Jest in combination with babel as jest does not yet natively work with ES6 modules without some pre-processing. 

I have also added some comments to the tests in the form of ToDo's, these are where I believe we may have bugs to squash (which I would be happy to help remedy).

### CODE REVIEW

**Comment by jeff-zucker** [comment]
Looks fantastic.  I get the following : 

    Details:

    /home/jeff/Dropbox/Web/solid/solid-uix/src/utils.test.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){import { initLibraries, localWebid, str2node, str2stm, getNodeFromFieldValue, curie } from './utils';
                                                                                      ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1495:14)

----------|---------|----------|---------|---------|-------------------
File      | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
----------|---------|----------|---------|---------|-------------------
All files |       0 |        0 |       0 |       0 |                   
----------|---------|----------|---------|---------|-------------------
Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.535 s
Ran all test suites.

**Comment by PSFW** [comment]
Ok, this has proved very fiddly so far so this doesn't surprise me haha.
Please could you tell me which version of node you are using?

**Comment by jeff-zucker** [comment]
I don't know how this is usually done, but it won't let me merge without resolving the conflicts in the 30,000 lines of package-lock.json.  Is there any way around hand editing that?

**Comment by PSFW** [comment]
Oh sorry I thought I'd resolved them all, I'll resolve this

**Comment by jeff-zucker** [comment]
I hand copied everything but the package.lock, ran npm ci then npm run test and 31/32 passed.  Thanks so much for the tests!

**Comment by PSFW** [comment]
No problem! I'm happy to help, in the end to resolve this I did the following:
- synced my fork
- checkout out main locally and pulled
- checkout out my test branch and rebased onto main
- ran merge tools and pushed my changes

**Comment by jeff-zucker** [comment]
Thanks much!  Heads up - I have seen the light about web-components and will probably re-write everything to use them rather than the `data-uix=""` style.  Shouldn't impact the low-level stuff.

**Comment by PSFW** [comment]
hahaha, I understand. This library has alot of potential, it seems to be the one library that combines a data source and a template together, having a prewritten template (as a web component) with defined slots in it has some traction. This also does forms which I have a strong desire for.

Templates being front and centre as a way of displaying variables and querying is something I was thinking about for a previous project (implementing an open version of [this](https://uispin.org/ui.html#example) - which would replace strings with web component names), that's what put me on the search when I found this project.

I'm keen to help in anyway I can, writing tests has helped familiarise myself with the repo so I can continue to add them for the helper functions. 
Shall I create Issues for the potential bugs that I've tagged with ToDo comments?

**Comment by jeff-zucker** [comment]
Forms are a big area and there's lots to do there.  My overall goal is to expose all of the SolidOS stack - rdflib, solid-ui, mashlib as web-components so that will include the simple querying, full SPARQL, and lots of forms fun .  Solid-ui forms are fantastically powerful and even more difficult to follow, you might want to start looking at them.  

Yes, please, file any issues and PRs you can think of.  I welcome your help at any level, please don't hesitate to make suggestions.  SWP does look very similar.  

Also, I'd value your opinion on web components.  I am getting some pushback, also recommendations to use various frameworks.  You should join the conversation over at https://app.gitter.im/#/room/#solid_solidos:gitter.im.

**Pull request merged**
